### PR TITLE
Fix failing tests due to change in core steps: add table headings

### LINKED ISSUE #300: Acceptance test fails due to core changes
https://drone.owncloud.com/owncloud/notifications/987/12/10

### PR DESCRIPTION
**Pull request by dpakach**
Fixes #300 

Fix failing tests after the change in core by owncloud/core#36651

Add headings to the tables in feature files.

Note: This needs additional changes on core to pass. This will pass on 2020-01-02 (at earliest)

### CODE REVIEW

**Comment by phil-davis** [comment]
still failing https://drone.owncloud.com/owncloud/notifications/988/12/10 :(

**Comment by dpakach** [comment]
> still failing https://drone.owncloud.com/owncloud/notifications/988/12/10 :(

@phil-davis this will need some changes in core. Will pass tomorrow.

**Comment by phil-davis** [comment]
@dpakach I think we did not finish the core changes yesterday?

**Comment by phil-davis** [comment]
I restarted drone - looks good now.

**Pull request merged**
