### PR TITLE
Add screenshots to the readme

### LINKED ISSUE #26: Provide Screenshots in Readme.md
Please :)

So everyone can imaginge better what this app does without the need to check it out and install.

Thanks!

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #26 

@stefan-niedermann

### CODE REVIEW

**Comment by nickvergessen** [comment]
https://github.com/owncloud/notifications/blob/issue-26-screenshots-in-readme/README.md This is how ti looks now

**Comment by stefan-niedermann** [comment]
great! thank you. :) :+1:

**Comment by Henni** [comment]
@nickvergessen you removed some code examples. We should move them to the developer documentation.

**Comment by nickvergessen** [comment]
I moved them to the wiki two weeks ago, they just duplicated the pages.
Instead it now hold links to the wiki pages: https://github.com/owncloud/notifications#notification-workflow

**Comment by Henni** [comment]
:+1:

**Pull request merged**
