### PR TITLE
Add "hello" in the mail templates

### PR DESCRIPTION
**Pull request by jvillafanez**
Include a "Hello" line in the templates. Partially fixes https://github.com/owncloud/core/issues/31876

### CODE REVIEW

**Comment by jvillafanez** [comment]
Backport in https://github.com/owncloud/notifications/pull/209

**Comment by PVince81** [comment]
did you test ? doesn't look that good:

```
Hello,
"user1" invited you to view "fu"

See http://localhost/owncloudtest/index.php/f/169 on ownCloud for more information
```

add another br below "Hello"

**Comment by jvillafanez** [comment]
It doesn't look that bad to me... the "hello" can be considered part of the message.

**Comment by pmaier1** [comment]
> hmm, depends. most official emails I receive have a blank line between greetings and the body and also a blank line before the signature.

Agree. Please add a blank line as suggested.

**Pull request merged**
