### PR TITLE
[stable10] Fix notification not being sent by email if system cron is set

### PR DESCRIPTION
**Pull request by jvillafanez**
Backport of https://github.com/owncloud/notifications/pull/189 to stable10

### CODE REVIEW

**Comment by phil-davis** [comment]
@jvillafanez this little change seems to already be in ``stable10`` here, done in:
https://github.com/owncloud/notifications/pull/188/files#diff-41624482113d3270166911ed842f2fe7R134
???

**Comment by jvillafanez** [comment]
Not sure what happened here, maybe merging things in wrong order (?)

The change for this PR is already in stable10 somehow, so I vote for closing this PR.

**Comment by PVince81** [comment]
@jvillafanez please close after confirming that the diff becomes empty when resolving this conflict

**Comment by jvillafanez** [comment]
Yes, git doesn't detect any change after resolving the conflict. 👍

**Pull request closed without merging**
