### PR TITLE
Move OCS calls to app framework - consumes less resources

### PR DESCRIPTION
**Pull request by DeepDiver1975**
requires https://github.com/owncloud/core/pull/28168

### CODE REVIEW

**Comment by PVince81** [comment]
which part of the notifications app requires custom headers ? this is not directly visible in this diff but I guess it's buried somewhere else in the app ?

**Comment by DeepDiver1975** [comment]
etagg is transmitted - https://github.com/owncloud/notifications/pull/98/files#diff-30970b8579f39524067cc33fa0f56833L103

**Comment by PVince81** [comment]
Ok then, but CI is failing

**Comment by PVince81** [comment]
never mind, needs core PR to be merged for CI.

:+1: if CI passes after that

**Comment by PVince81** [comment]
some failures in multiple targets, for example:
```
There were 6 failures:

1) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testGetNotification with data set #0 (42, 'username1', array('$notification'))

Expectation failed for method name is equal to <string:getById> when invoked 1 time(s)

Parameter 0 for invocation OCA\Notifications\Handler::getById(Array (...), 'username1') does not match expected value.

Array (...) does not match expected type "integer".

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:121

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:309

2) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testGetNotification with data set #1 (21, 'username2', array('$notification'))

Expectation failed for method name is equal to <string:getById> when invoked 1 time(s)

Parameter 0 for invocation OCA\Notifications\Handler::getById(Array (...), 'username2') does not match expected value.

Array (...) does not match expected type "integer".

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:121

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:309

3) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testGetNotificationNoId with data set #1 (true, array(), false, null)

OCA\Notifications\Handler::getById(Array (), 'username') was not expected to be called.

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:121

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:350

4) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testDeleteNotification with data set #0 (42, 'username1')

Expectation failed for method name is equal to <string:deleteById> when invoked 1 time(s)

Parameter 0 for invocation OCA\Notifications\Handler::deleteById(Array (...), 'username1') does not match expected value.

Array (...) does not match expected type "integer".

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:150

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:375

5) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testDeleteNotification with data set #1 (21, 'username2')

Expectation failed for method name is equal to <string:deleteById> when invoked 1 time(s)

Parameter 0 for invocation OCA\Notifications\Handler::deleteById(Array (...), 'username2') does not match expected value.

Array (...) does not match expected type "integer".

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:150

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:375

6) OCA\Notifications\Tests\Unit\Controller\EndpointControllerTest::testDeleteNotificationNoId

OCA\Notifications\Handler::deleteById(Array (), 'username') was not expected to be called.

/home/travis/build/owncloud/core/apps/notifications/lib/Controller/EndpointController.php:150

/home/travis/build/owncloud/core/apps/notifications/tests/Unit/Controller/EndpointControllerTest.php:387

FAILURES!

Tests: 36, Assertions: 104, Failures: 6.
```

**Pull request merged**
