### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by nickvergessen**
@tomneedham managed to rebase it

### CODE REVIEW

**Comment by jancborchardt** [comment]
I will see to improve this.

**Comment by jancborchardt** [comment]
It looks like this for me:
capture du 2015-09-08 15-11-31
Am pretty sure this is not intended.

* [ ] remove the `div` part preceding every class. This level of specificity is not needed
* [ ] use same animation speed (50ms afaik) as the user and app menu dropdown
* [ ] close menu when user and app menu is opened, and vice versa cc @PVince81 
* [ ] when there are no notifications, show no scrollbar, and show a nice `.emptycontent` style message like in files for empty folders

@nickvergessen can you do some of that? I can do style details then, but this seems not done technically yet.

**Comment by nickvergessen** [comment]
not atm since I'm busy with other stuff

**Comment by jancborchardt** [comment]
Ok. I mean I can’t really work on it when it’s not done code-wise really. Also, I need a way to mock notifications to properly style them.

**Comment by nickvergessen** [comment]
> Also, I need a way to mock notifications to properly style them.

Checkout the notification-manager branch in core and do a remote share with yourself

**Comment by nickvergessen** [comment]
Fixed some of the stuff (although I guess you could have done that as well)
For the remaining tasks we need some time from PVinc or another JS guru

**Comment by tomneedham** [comment]
We also need to handle sorting (as mentioned in the todo somewhere) as we just pretend them into the Dom so it depends on the ordering from the API currently

**Comment by nickvergessen** [comment]
The API sorts them correctly :P *trust ™*

**Comment by jancborchardt** [comment]
@nickvergessen btw, we don’t need/want a counter in the header, only two icons: regular notification icon, and a slightly different one if there are unread notifications.

**Comment by nickvergessen** [comment]
Rebased to fix the Travis and Scrutinizer fails

**Comment by nickvergessen** [comment]
@jancborchardt I've done all I can here

**Comment by jancborchardt** [comment]
@nickvergessen I added the icons for the default and for when there are new notifications. Can you hook that up?

**Comment by nickvergessen** [comment]
bildschirmfoto vom 2015-09-15 16 09 31

**Comment by nickvergessen** [comment]
I'll merge this now, so we finally have a UI in master.

Let's fix the remaining stuff in new PRs

**Pull request merged**
