### PR TITLE
occ: Provide arguments for link and linktext

### PR DESCRIPTION
**Pull request by guruz**
For https://github.com/owncloud/client/pull/6240

Do you agree with @dragotin 's idea from the client PR to put the link text into the link property too?

```
notifications:generate [-u|--user USER] [-g|--group GROUP] [--] <subject> [<message>] [<link>] [<linktext>]
```

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Add my comment to the client pr - I consider this magic whitespace as fishy

**Comment by jvillafanez** [comment]
I think everyone agree that the `setLink` expects an html link to be used as parameter, so anything set there should be interpreted as such. Changing the meaning doesn't seem a good option.
There is the additional problem of lacking specifications (the interface doesn't say anything about whether the link should be urlencoded or not, or who should ensure that), so a whitespace could be a valid character as part of the link if we consider that the encoding should be done by the one rendering the link.

I'd prefer to remove the text link for now until we have proper support for it. Just setting the link should be good enough.

Regardless the code itself, I'm not sure if the link should be an argument or an option. Argument feels like it's mandatory even though it isn't.

**Comment by guruz** [comment]
@jvillafanez @DeepDiver1975 PR updated

**Comment by DeepDiver1975** [comment]
@guruz please backport to stable10 - THX

**Comment by guruz** [comment]
@DeepDiver1975 the commit was in stable10.

**Comment by guruz** [comment]
are you merging stable10 to master usually?

**Comment by PVince81** [comment]
@guruz not yet for bundled apps. For marketplace apps, yes

**Comment by mmattel** [comment]
https://github.com/owncloud/documentation/pull/4070

**Pull request merged**
