### PR TITLE
Prepare object id to be a string

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Depends on https://github.com/owncloud/core/pull/20682

@MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by rullzer** [comment]
Travis is not happy :(

**Comment by nickvergessen** [comment]
that is due to master (missing the branch while testing)

**Comment by rullzer** [comment]
tested locally and all is fine indeed. :+1:

**Comment by nickvergessen** [comment]
@rullzer jenkins happy now, merging

**Pull request merged**
