### PR TITLE
Only add the JS and CSS when not on public pages

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix owncloud/core#19406

@davitol @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
another approach would be to detect `incognitoMode` (but that will be removed eventually)

Makes sense :+1:

**Comment by nickvergessen** [comment]
Well I thought about checking the session as well, but that should be done additionally. We don't need to load the stuff on OCS, WebDAV or other requests either ;)

**Comment by davitol** [comment]
:+1: WFM

**Comment by Quix0r** [comment]
The message is still coming with latest stable release. Maybe worth to open new ticket.

Now I get
````
# sudo -u vu2001 ./occ maintenance:singleuser --off
`An unhandled exception has been thrown:
exception 'OCP\AppFramework\QueryException' with message 'Could not resolve OCA\News\Command\Updater\AllFeeds! Class OCA\News\Service\FeedService does not exist' in /var/www/.../lib/private/appframework/utility/simplecontainer.php:89
````

**Comment by nickvergessen** [comment]
That is unrelated to this app, try reporting your issue in https://github.com/owncloud/news

**Pull request merged**
