### PR TITLE
Stable10 fix actions

### PR DESCRIPTION
**Pull request by PVince81**
Backport https://github.com/owncloud/notifications/pull/108 to stable10

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Is there an easy way to test?

**Comment by PVince81** [comment]
@DeepDiver1975 see original ticket: federated share.

Before fix: escape looks shit, cannot click Accept
After fix: no more shit escape, click Accept works

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 see original ticket: federated share.

isnt there an easier way to test this? extend the notificatinons:generate command?

**Comment by PVince81** [comment]
@DeepDiver1975 if the notifications:generate command allows you to create buttons, then you could use that, yes. Any make sure you have double quotes in your messages.

**Comment by DeepDiver1975** [comment]
No idea if it really makes sense to add actions to the occ command. actions require a link which is called by the ui. can be messy to add links via the command.

**Comment by PVince81** [comment]
@DeepDiver1975 in this case the answer to the question "isnt there an easier way to test this?" is **no** ;-)

**Comment by DeepDiver1975** [comment]
anyway - I have tested this 👍

**Pull request merged**
